ARACKIRALAMA SON/MvcKutuphane/Controllers/KiraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;
namespace MvcKutuphane.Controllers
{
    public class KiraController : Controller
    {
        // GET: Odunc
        ARACEntities db = new ARACEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLHAREKET.Where(x => x.ISLEMDURUM == false).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KiraVer()
        {
            List<SelectListItem> deger1 = (from x in db.TBLUYELER.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.AD + " " + x.SOYAD,
                                               Value = x.ID.ToString()
                                           }).ToList();
            List<SelectListItem> deger2 = (from y in db.TBLARACLAR.Where(x => x.DURUM == true).ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.PLAKA,
                                               Value = y.ID.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from z in db.TBLPERSONEL.ToList()
                                           select new SelectListItem
                                           {
                                               Text = z.PERSONEL,
                                               Value = z.ID.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }
        [HttpPost]
        public ActionResult KiraVer(TBLHAREKET p)
        {
            var d1 = db.TBLUYELER.Where(x => x.ID == p.TBLUYELER.ID).FirstOrDefault();
            var d2 = db.TBLARACLAR.Where(y => y.ID == p.TBLARACLAR.ID).FirstOrDefault();
            var d3 = db.TBLPERSONEL.Where(z => z.ID == p.TBLPERSONEL.ID).FirstOrDefault();
            p.TBLUYELER = d1;
            p.TBLARACLAR = d2;
            p.TBLPERSONEL = d3;
            db.TBLHAREKET.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Kiraiade(TBLHAREKET p)
        {
            var odn = db.TBLHAREKET.Find(p.ID);
            DateTime d1 = DateTime.Parse(odn.IADETARIH.ToString());
            DateTime d2 = DateTime.Parse(odn.ALISTARIH.ToString());
            TimeSpan d3 = d1 - d2;
            ViewBag.dgr = d3.TotalDays;
            return View("Kiraiade", odn);
        }
        public ActionResult KiraGuncelle(TBLHAREKET p)
        {
            var hrk = db.TBLHAREKET.Find(p.ID);
            hrk.UYEGETIRTARIH = p.UYEGETIRTARIH;
            hrk.ISLEMDURUM = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ARACKIRALAMA SON/MvcKutuphane/Views/Kira/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLHAREKET>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Kiradaki Araçlar Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th>İşlem ID</th>
        <th>Plaka No</th>
        <th>Üye</th>
        <th>Personel</th>
        <th>Alış Tarihi</th>
        <th>İade Tarihi</th>
        <th>İade Al</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.ID</td>
            <td>@k.TBLARACLAR.PLAKA</td>
            <td>@k.TBLUYELER.AD&nbsp @k.TBLUYELER.SOYAD</td>
            <td>@k.TBLPERSONEL.PERSONEL</td>
            <td>@Convert.ToDateTime(k.ALISTARIH).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(k.IADETARIH).ToString("dd/MM/yyyy")</td>
            <td><a href="/Kira/Kiraiade/@k.ID" class="btn btn-default" style="background-color:#64d8ca; color:white">Aracı İade Et</a></td>
        </tr>
    }
</table>

ARACKIRALAMA SON/MvcKutuphane/Views/Kira/KiraVer.cshtml
@model MvcKutuphane.Models.Entity.TBLHAREKET
@{
    ViewBag.Title = "KiraVer";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Üye ID</label>
   
        @Html.DropDownListFor(k => k.TBLUYELER.ID, (List<SelectListItem>)ViewBag.dgr1,new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Plaka No</label>
    
        @Html.DropDownListFor(k => k.TBLARACLAR.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Personel ID</label>
    
        @Html.DropDownListFor(k => k.TBLPERSONEL.ID, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Araç Alış Tarihi</label>
        <input type="text" class="form-control" name="ALISTARIH" value="@DateTime.Now.ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <label>Araç İade Tarihi</label>
        <input type="text" class="form-control" name="IADETARIH" value="@DateTime.Now.AddDays(7).ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-group" style="background-color:#a330b5; color:white">Aracı Kiraya Ver</button>
        <input type="hidden" value="False" name="ISLEMDURUM" />
    </div>
</form>

ARACKIRALAMA SON/MvcKutuphane/Views/Kira/Kiraiade.cshtml
@model MvcKutuphane.Models.Entity.TBLHAREKET
@{
    ViewBag.Title = "Kiraiade";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("KiraGuncelle", "Kira", FormMethod.Post))
{
    <div style=" margin-bottom:15px"></div>
    <div class="form-group">
        <label>Hareket ID</label>
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
        <br />
        <label>Plaka No</label>
        @Html.TextBoxFor(k => k.TBLARACLAR.ID, new { @class = "form-control" })
        <br />
        <label>Üye</label>
        @Html.TextBoxFor(k => k.TBLUYELER.AD, new { @class = "form-control" })
        <br />
        <label>Personel</label>
        @Html.TextBoxFor(k => k.TBLPERSONEL.PERSONEL, new { @class = "form-control" })
        <br />
        <label>Alış tarihi</label>
        @Html.TextBoxFor(k => k.ALISTARIH, "{0: dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Normal İade tarihi</label>
        @Html.TextBoxFor(k => k.IADETARIH, "{0: dd.MM.yyyy}", new { @class = "form-control" })
        <br />
        <label>Üyenin Getirdiği Tarih</label>
        <input type="text" class="form-control" name="UYEGETIRTARIH" value="@DateTime.Now.ToShortDateString()" />
        <br />
        <label>Kiradaki Gün Sayısı</label>
        <input type="text"class="form-control" id="Gecinput" value="@ViewBag.dgr" />
     
    </div>
    <div>
        <button class="btn btn-group" style="background-color:#64d8ca; color:white">Kirayı Sonlandır</button>
    </div>
}